[[pages]]
path = "aqi_detection.py"
name = "Air Quality Index"
icon = ":four_leaf_clover:"

[[pages]]
path = "weatherforecast.py"
name = "Daily Weather"
icon = ":mostly_sunny:"

[[pages]]
path = "about.py"
name = "About"
icon = ":star:"

[[pages]]
path = "me.py"
name = "Example Five"
icon = "🧰"
url_path = "a_very_long_page_title"