[[pages]]
path = "aqi_detection.py"
name = "Air Quality"
icon = "📄"


[[pages]]
path = "about.py"
name = "Daily Weather"
icon = "📖"

[[pages]]
path = "me.py"
name = "Example Five"
icon = "🧰"
url_path = "a_very_long_page_title"